export const DEFINE_MENU_SIZE="DEFINE_MENU_SIZE"
export const OPEN_ANIMATION_MENU="OPEN_ANIMATION_MENU"
export const CLOSE_ANIMATION_MENU="CLOSE_ANIMATION_MENU"
export const SET_ANIMATION_PATH="SET_ANIMATION_PATH"