export const UPLOAD_SPRITES='UPLOAD_SPRITES'
export const ADD_SPRITE='ADD_SPRITE'
export const DELETE_SPECIFIC_SPRITE='DELETE_SPECIFIC_SPRITE'
export const SET_CURRENT_ANIM_SPRITE='SET_CURRENT_ANIM_SPRITE'